apiVersion: v1
kind: Service
metadata:
  name: ecommerce
  namespace: ecommerce-monolith
spec:
  selector:
    app: ecommerce
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080